// <auto-generated />
using HouseplantAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseplantAPI.Migrations
{
    [DbContext(typeof(HouseplantApiDbContext))]
    partial class HouseplantApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HouseplantAPI.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Foliage"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Flowering"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Succulent"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cacti"
                        });
                });

            modelBuilder.Entity("HouseplantAPI.Entities.Houseplant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leaves")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Houseplants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Leaves = 3,
                            Name = "Monstera"
                        });
                });

            modelBuilder.Entity("HouseplantAPI.Entities.Houseplant", b =>
                {
                    b.HasOne("HouseplantAPI.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
