GET http://localhost:5188/houseplant

###
GET http://localhost:5188/houseplant/6

###
POST http://localhost:5188/houseplant
Content-Type: application/json

{
    "name": "String of Pearls",
    "leaves": 50,
    "categoryId": 3
}

###
PUT http://localhost:5188/houseplant/5
Content-Type: application/json

{
    "name": "Jade Plant",
    "leaves": 41,
    "categoryId": 3
}

###
DELETE http://localhost:5188/houseplant/6


