GET http://localhost:5210/games

###
GET http://localhost:5210/games/2

###
POST http://localhost:5210/games
Content-Type: application/json

{
  "name": "Valorant",
  "genreId": 1,
  "price": 10.99,
  "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5210/games/3
Content-Type: application/json

{
  "name": "Valheim",
  "genreId": 2,
  "price": 35.99,
  "releaseDate": "2023-05-01"
}

###
DELETE http://localhost:5210/games/4
